import { defineConfig } from "tsup";

export default defineConfig([
  {
    entryPoints: ["runtime/index.ts"],
    format: ["cjs", "esm"],
    minify: true,
    sourcemap: true,
    clean: true,
    external: ["react", "next-yak/context"],
    target: "es2022",
    outDir: "dist",
  },
  {
    entryPoints: ["runtime/index.ts"],
    format: ["cjs", "esm"],
    dts: {
      only: true,
    },
    external: ["react"],
    target: "es2022",
    outDir: "dist",
  },
  {
    entryPoints: ["runtime/internals/index.ts"],
    format: ["cjs", "esm"],
    minify: true,
    sourcemap: true,
    clean: true,
    external: ["react"],
    target: "es2022",
    outDir: "dist/runtime-internals",
  },
  {
    entryPoints: ["static/index.ts"],
    format: ["cjs", "esm"],
    minify: true,
    sourcemap: true,
    clean: true,
    dts: true,
    external: ["react"],
    target: "es2022",
    outDir: "dist/static",
  },
  {
    entryPoints: ["runtime/context/baseContext.tsx"],
    format: ["cjs", "esm"],
    minify: false,
    sourcemap: true,
    clean: false,
    dts: true,
    external: ["react"],
    target: "es2022",
    outDir: "dist/context",
  },
  {
    entryPoints: ["runtime/context/index.tsx"],
    format: ["cjs", "esm"],
    minify: false,
    sourcemap: true,
    clean: false,
    dts: true,
    external: ["react"],
    target: "es2022",
    outDir: "dist/context",
  },
  {
    entryPoints: ["runtime/context/index.server.tsx"],
    format: ["cjs", "esm"],
    minify: false,
    sourcemap: true,
    clean: false,
    external: ["react", "next-yak/context/baseContext", "./index.js"],
    target: "es2022",
    outDir: "dist/context",
  },
  {
    entryPoints: ["withYak/index.ts"],
    format: ["cjs"],
    minify: false,
    sourcemap: true,
    clean: false,
    dts: true,
    external: ["../loaders/tsloader.cjs", "../loaders/cssloader.cjs"],
    target: "es2022",
    outDir: "withYak",
  },
]);
