packages:
  - packages/*
catalogs:
  core:
    "@babel/core": 7.26.0
    "@babel/plugin-syntax-typescript": 7.25.9
    "@swc/counter": 0.1.3

  dev:
    "@babel/preset-typescript": 7.26.0
    "@babel/types": 7.26.3
    "@changesets/cli": 2.27.9
    "@codspeed/benchmark.js-plugin": 4.0.0
    "@monaco-editor/react": 4.6.0
    "@next/mdx": 15.1.3
    "@shikijs/monaco": 1.24.4
    "@shikijs/transformers": 1.24.4
    "@swc/core": 1.9.2
    "@testing-library/dom": 10.4.0
    "@testing-library/jest-dom": 6.6.3
    "@testing-library/react": 16.1.0
    "@types/babel__core": 7.20.5
    "@types/benchmark": 2.1.5
    "@types/jest": 29.5.14
    "@types/mdx": 2.0.13
    "@types/node": 22.10.2
    "@types/react": 19.0.2
    "@types/react-dom": 19.0.2
    "@types/webpack": 5.28.5
    "@typescript-eslint/rule-tester": 8.23.0
    "@typescript-eslint/utils": 8.23.0
    "@vitejs/plugin-react": 4.3.4
    autoprefixer: 10.4.20
    benchmark: 2.1.4
    fast-glob: 3.3.2
    fumadocs-core: 14.6.8
    fumadocs-mdx: 11.2.1
    fumadocs-openapi: 5.10.6
    fumadocs-twoslash: 2.0.2
    fumadocs-ui: 14.6.8
    jest: 29.7.0
    jest-environment-jsdom: 29.7.0
    jsdom: 25.0.1
    memfs: 4.15.1
    next: 15.1.3
    next-themes: 0.4.4
    postcss: 8.4.49
    postcss-nested: 7.0.2
    prettier: 3.0.3
    raw-loader: 4.0.2
    react: 19.0.0
    react-dom: 19.0.0
    react-resizable-panels: 2.1.7
    shiki: 1.24.4
    shiki-magic-move: 0.5.2
    styled-components: 6.1.13
    swc-loader: 0.2.6
    tailwindcss: 3.4.17
    tree-kill: 1.2.2
    tsup: 8.3.5
    typescript: 5.7.2
    unionfs: 4.5.4
    vite: 6.0.6
    vitest: 2.1.8
    webpack: 5.97.1
